#!/bin/bash
#set -x
# arguments should be
# $1 = coadded dada key
# $2 = buffersize 
# $3 = write_fb
# $4 = nbit
PACKAGE_DIR=/home/vlite-master/surya
ROOT=vd10
# ------ slackpush
if hash ag_slackpush 2> /dev/null; then
  ag_slackpush "Coadder start $(date +"%Y-%m-%d %T")"
fi
# ------ slackpush
# Create buffer at root
#ssh ${ROOT} "/mnt/ssd/bin/dada_db -k ${1} -b ${2} -n 8 -l"
# MPICALL
# MODE = 1 --> Full array
# MODE = 2 --> Debug array
MODE=1
DC="${PACKAGE_DIR}/bin/agdadacoadd -K ${1} -b ${4} -s ${2} -f ${3}"
if [ ${MODE} -eq 1 ]
then
 # Full array
mpirun  --tune ${PACKAGE_DIR}/vlite-fast/config/coadd_mca.conf \
  --output-filename ${PACKAGE_DIR}/logs   --display-map     \
  --oversubscribe\
  --hostfile ${PACKAGE_DIR}/vlite-fast/config/fullcoaddhost \
 -host vd11,vd1,vd2,vd4,vd5,vd6,vd7,vd8,vd9,vd10,vd12       \
 --map-by ppr:1:node ${DC} -k 46             :                \
 -host vd8,vd9,vd10,vd12                                        \
 --map-by ppr:1:node ${DC} -k 56
elif [ ${MODE} -eq 11 ]
then
 # Full array
mpirun  --tune ${PACKAGE_DIR}/vlite-fast/config/coadd_mca.conf \
  --output-filename ${PACKAGE_DIR}/logs   --display-map     \
  --oversubscribe\
  --hostfile ${PACKAGE_DIR}/vlite-fast/config/fullcoaddhost \
 -host vd11,vd1,vd2,vd3,vd4,vd5,vd7,vd10       \
 --map-by ppr:1:node ${DC} -k 46 :   \
 -host vd12,vd8,vd9,vd10                                \
 --map-by ppr:1:node ${DC} -k 56 
elif [ ${MODE} -eq 2 ]
then
echo "do this"
# Debug array
elif [ ${MODE} -eq 3 ]
 # Full array - vd8,vd9
mpirun  --tune ${PACKAGE_DIR}/vlite-fast/config/coadd_mca.conf \
  --output-filename ${PACKAGE_DIR}/logs   --display-map     \
  --oversubscribe\
  --hostfile ${PACKAGE_DIR}/vlite-fast/config/fullcoaddhost \
 -host vd10,vd1,vd3,vd5,vd8,vd9,vd11,vd12       \
 --map-by ppr:1:node ${DC} -k 46             :                \
 -host vd8,vd9,vd11,vd12                                      \
 --map-by ppr:1:node ${DC} -k 56
then
# 8Debug array
mpirun \
 --display-map --output-filename ${PACKAGE_DIR}/logs/debug8 -host vd12,vd7,vd8,vd9,vd11,vd10 --map-by ppr:1:node ${DC} -k 56  :    \
 --output-filename ${PACKAGE_DIR}/logs/debug9 -host vd2,vd5 --map-by ppr:1:node ${DC} -k 46
#mpirun -v --output-filename ${PACKAGE_DIR}/logs/debug8 -host vd10 -np 1 ${DC} -k 56
elif [ ${MODE} -eq 5 ]
then
# 8Debug array
mpirun \
 --display-map --output-filename ${PACKAGE_DIR}/logs/smalldebug -host vd12,vd10,vd7,vd2 --map-by ppr:1:node ${DC} -k 46
elif [ ${MODE} -eq 6 ]
then
# 6Debug array
mpirun --hostfile ${PACKAGE_DIR}/vlite-fast/config/fullcoaddhost\
 --display-map --output-filename ${PACKAGE_DIR}/logs/debug6 -host vd10,vd9,vd2,vd3 --map-by ppr:1:node ${DC} -k 46 :\
 -host vd10,vd9 --map-by ppr:1:node ${DC} -k 56
fi
# Destroy buffer after use
#ssh ${ROOT} "/mnt/ssd/bin/dada_db -k ${1} -d"
# ------ slackpush
if hash ag_slackpush 2> /dev/null; then
  ag_slackpush "Coadder tstop $(date +"%Y-%m-%d %T")"
fi
