#!/bin/bash
#set -x
# arguments should be
# no-args

PACKAGE_DIR=/home/vlite-master/surya
MPIRUN="mpirun"

DC="python update_pkl.py -v -c"

mpirun  --tune ${PACKAGE_DIR}/vlite-fast/config/coadd_mca.conf \
 -host vd11,vd1,vd2,vd3,vd4,vd5,vd6,vd7,vd8,vd9,vd10,vd12      \
 --map-by ppr:1:node \
 ${DC}
